

import type { ResumeData, ResumeDocument } from "./types";


export function toJSON(doc: ResumeDocument): string {
  return JSON.stringify(doc, null, 2);
}









function texEscape(s: string | undefined): string {
  if (!s) return "";
  return s
    .replace(/\\/g, "\\textbackslash{}")
    .replace(/&/g, "\\&")
    .replace(/%/g, "\\%")
    .replace(/\$/g, "\\$")
    .replace(/#/g, "\\#")
    .replace(/_/g, "\\_")
    .replace(/\{/g, "\\{")
    .replace(/\}/g, "\\}")
    .replace(/~/g, "\\textasciitilde{}")
    .replace(/\^/g, "\\textasciicircum{}")
    
    .replace(/[\u2018\u2019]/g, "'")
    .replace(/[\u201C\u201D]/g, '"')
    
    .replace(/\u2013/g, "--")
    .replace(/\u2014/g, "---")
    
    .replace(/[^\x00-\x7F]/g, "");
}


function texDate(s: string | undefined): string {
  if (!s) return "";
  const m = s.match(/^(\d{4})-(\d{1,2})$/);
  if (m) {
    const months = [
      "January","February","March","April","May","June",
      "July","August","September","October","November","December",
    ];
    return `${months[parseInt(m[2], 10) - 1]} ${m[1]}`;
  }
  return s;
}

export type LatexVariant = "jake" | "moderncv" | "altacv";

export type PageSize = "letter" | "a4" | "legal" | "a3" | "tabloid" | "executive";

export const PAGE_SIZES: { id: PageSize; label: string; dimensions: string }[] = [
  { id: "letter", label: "US Letter", dimensions: '8.5×11"' },
  { id: "a4", label: "A4", dimensions: "210×297mm" },
  { id: "legal", label: "US Legal", dimensions: '8.5×14"' },
  { id: "a3", label: "A3", dimensions: "297×420mm" },
  { id: "tabloid", label: "Tabloid", dimensions: '11×17"' },
  { id: "executive", label: "Executive", dimensions: '7.25×10.5"' },
];

const PAPER_DIM: Record<PageSize, string> = {
  letter: "letter",
  a4: "A4",
  legal: "legal",
  a3: "A3",
  tabloid: "tabloid",
  executive: "executive",
};

const TEX_PAPER: Record<PageSize, string> = {
  letter: "letterpaper",
  a4: "a4paper",
  legal: "legalpaper",
  a3: "a3paper",
  tabloid: "tabloidpaper",
  executive: "executivepaper",
};

export function toLatex(doc: ResumeDocument, variant: LatexVariant = "jake", pageSize: PageSize = "letter"): string {
  const d = doc.data;
  const accent = doc.meta.accent || "#0f766e";

  if (variant === "altacv") return altaCV(d, accent);
  if (variant === "moderncv") return modernCV(d, accent);
  return jakesResume(d, accent, pageSize);
}





function jakesResume(d: ResumeData, accent: string, pageSize: PageSize = "letter"): string {
  const hex = accent.replace("#", "").toUpperCase();
  const paperSize = TEX_PAPER[pageSize];
  const lines: string[] = [];

  
  lines.push("% Resume generated by Resumind — based on Jake Gutierrez's template");
  lines.push("% https://github.com/jakegut/resume — MIT License");
  lines.push("% Compile with: pdflatex resume.tex  (or XeLaTeX for custom fonts)");
  lines.push("");
  lines.push(`\\documentclass[${paperSize},11pt]{article}`);
  lines.push("");
  lines.push("\\usepackage{latexsym}");
  lines.push("\\usepackage[empty]{fullpage}");
  lines.push("\\usepackage{titlesec}");
  lines.push("\\usepackage[usenames,dvipsnames]{color}");
  lines.push("\\usepackage{verbatim}");
  lines.push("\\usepackage{enumitem}");
  lines.push("\\usepackage{hyperref}");
  lines.push("\\usepackage{fancyhdr}");
  lines.push("\\usepackage[english]{babel}");
  lines.push("\\usepackage{tabularx}");
  lines.push("% glyphtounicode: ensures PDF text is ATS-extractable (pdflatex only)");
  lines.push("\\ifdefined\\pdfgentounicode");
  lines.push("  \\input{glyphtounicode}");
  lines.push("  \\pdfgentounicode=1");
  lines.push("\\fi");
  lines.push("");
  
  lines.push("\\pagestyle{fancy}");
  lines.push("\\fancyhf{}");
  lines.push("\\fancyfoot{}");
  lines.push("\\renewcommand{\\headrulewidth}{0pt}");
  lines.push("\\renewcommand{\\footrulewidth}{0pt}");
  lines.push("");
  
  lines.push("\\addtolength{\\oddsidemargin}{-0.5in}");
  lines.push("\\addtolength{\\evensidemargin}{-0.5in}");
  lines.push("\\addtolength{\\textwidth}{1in}");
  lines.push("\\addtolength{\\topmargin}{-0.5in}");
  lines.push("\\addtolength{\\textheight}{1.0in}");
  lines.push("");
  lines.push("\\urlstyle{same}");
  lines.push("\\raggedbottom");
  lines.push("\\raggedright");
  lines.push("\\setlength{\\tabcolsep}{0in}");
  lines.push("");
  
  lines.push("\\titleformat{\\section}{");
  lines.push("  \\vspace{-4pt}\\scshape\\raggedright\\large");
  lines.push("}{}{0em}{}[\\color{black}\\titlerule \\vspace{-5pt}]");
  lines.push("");
  
  lines.push("");
  
  lines.push("\\newcommand{\\resumeItem}[1]{");
  lines.push("  \\item\\small{");
  lines.push("    {#1 \\vspace{-2pt}}");
  lines.push("  }");
  lines.push("}");
  lines.push("");
  lines.push("\\newcommand{\\resumeSubheading}[4]{");
  lines.push("  \\vspace{-2pt}\\item");
  lines.push("    \\begin{tabular*}{0.97\\textwidth}[t]{l@{\\extracolsep{\\fill}}r}");
  lines.push("      \\textbf{#1} & #2 \\\\");
  lines.push("      \\textit{\\small#3} & \\textit{\\small #4} \\\\");
  lines.push("    \\end{tabular*}\\vspace{-7pt}");
  lines.push("}");
  lines.push("");
  lines.push("\\newcommand{\\resumeSubSubheading}[2]{");
  lines.push("    \\item");
  lines.push("    \\begin{tabular*}{0.97\\textwidth}{l@{\\extracolsep{\\fill}}r}");
  lines.push("      \\textit{\\small#1} & \\textit{\\small #2} \\\\");
  lines.push("    \\end{tabular*}\\vspace{-7pt}");
  lines.push("}");
  lines.push("");
  lines.push("\\newcommand{\\resumeProjectHeading}[2]{");
  lines.push("    \\item");
  lines.push("    \\begin{tabular*}{0.97\\textwidth}{l@{\\extracolsep{\\fill}}r}");
  lines.push("      \\small#1 & #2 \\\\");
  lines.push("    \\end{tabular*}\\vspace{-7pt}");
  lines.push("}");
  lines.push("");
  lines.push("\\newcommand{\\resumeSubItem}[1]{\\resumeItem{#1}\\vspace{-4pt}}");
  lines.push("");
  lines.push("% Inner list bullet style (simplified for portability)");
  lines.push("\\renewcommand\\labelitemii{\\textbullet}");
  lines.push("");
  lines.push("\\newcommand{\\resumeSubHeadingListStart}{\\begin{itemize}[leftmargin=0.15in, label={}]}");
  lines.push("\\newcommand{\\resumeSubHeadingListEnd}{\\end{itemize}}");
  lines.push("\\newcommand{\\resumeItemListStart}{\\begin{itemize}}");
  lines.push("\\newcommand{\\resumeItemListEnd}{\\end{itemize}\\vspace{-5pt}}");
  lines.push("");
  lines.push("%-------------------------------------------");
  lines.push("\\begin{document}");
  lines.push("");

  
  lines.push("%----------HEADING----------");
  lines.push("\\begin{center}");
  lines.push(`    \\textbf{\\Huge \\scshape ${texEscape(d.contact.name)}} \\\\ \\vspace{1pt}`);
  const contactParts: string[] = [];
  if (d.contact.phone) contactParts.push(texEscape(d.contact.phone));
  if (d.contact.email) contactParts.push(`\\href{mailto:${texEscape(d.contact.email)}}{\\underline{${texEscape(d.contact.email)}}}`);
  if (d.contact.linkedin) contactParts.push(`\\href{https://${texEscape(d.contact.linkedin)}}{\\underline{${texEscape(d.contact.linkedin)}}}`);
  if (d.contact.github) contactParts.push(`\\href{https://${texEscape(d.contact.github)}}{\\underline{${texEscape(d.contact.github)}}}`);
  if (d.contact.website) contactParts.push(`\\href{https://${texEscape(d.contact.website)}}{\\underline{${texEscape(d.contact.website)}}}`);
  if (d.contact.location) contactParts.push(texEscape(d.contact.location));
  const contactLine = contactParts.join(" $|$ ");
  lines.push(`    \\small ${contactLine}`);
  lines.push("\\end{center}");
  lines.push("");

  
  if (d.experience.length) {
    lines.push("%-----------EXPERIENCE-----------");
    lines.push("\\section{Experience}");
    lines.push("  \\resumeSubHeadingListStart");
    for (const e of d.experience) {
      const eStart = texDate(e.startDate);
      const eEnd = e.current ? "Present" : texDate(e.endDate);
      const dates = eStart && eEnd ? `${eStart} -- ${eEnd}` : eStart || eEnd || "";
      lines.push(`    \\resumeSubheading`);
      lines.push(`      {${texEscape(e.role)}}{${texEscape(dates)}}`);
      lines.push(`      {${texEscape(e.company)}}{${texEscape(e.location || "")}}`);
      if (e.bullets.length) {
        lines.push(`      \\resumeItemListStart`);
        for (const b of e.bullets) lines.push(`        \\resumeItem{${texEscape(b)}}`);
        lines.push(`      \\resumeItemListEnd`);
      }
    }
    lines.push("  \\resumeSubHeadingListEnd");
    lines.push("");
  }

  
  if (d.projects.length) {
    lines.push("%-----------PROJECTS-----------");
    lines.push("\\section{Projects}");
    lines.push("    \\resumeSubHeadingListStart");
    for (const p of d.projects) {
      const tech = p.tech.length ? ` \\textbar{}\\ \\emph{${texEscape(p.tech.join(", "))}}` : "";
      const pStart = texDate(p.startDate);
      const pEnd = texDate(p.endDate);
      const dateRange = pStart && pEnd ? `${pStart} -- ${pEnd}` : pStart || pEnd || "";
      lines.push(`      \\resumeProjectHeading`);
      lines.push(`          {\\textbf{${texEscape(p.name)}}${tech}}{${texEscape(dateRange)}}`);
      if (p.bullets.length) {
        lines.push(`          \\resumeItemListStart`);
        for (const b of p.bullets) lines.push(`            \\resumeItem{${texEscape(b)}}`);
        lines.push(`          \\resumeItemListEnd`);
      }
    }
    lines.push("    \\resumeSubHeadingListEnd");
    lines.push("");
  }

  if (d.training?.length) {
    lines.push("%-----------TRAINING-----------");
    lines.push("\\section{Summer Training}");
    lines.push("  \\resumeSubHeadingListStart");
    for (const t of d.training) {
      const start = texDate(t.startDate);
      const end = texDate(t.endDate);
      const dates = start && end ? `${start} -- ${end}` : start || end || "";
      lines.push(`    \\resumeSubheading`);
      lines.push(`      {${texEscape(t.title)}}{${texEscape(dates)}}`);
      lines.push(`      {${texEscape(t.organization || "")}}{}`);
      if (t.bullets.length) {
        lines.push(`      \\resumeItemListStart`);
        for (const b of t.bullets) lines.push(`        \\resumeItem{${texEscape(b)}}`);
        lines.push(`      \\resumeItemListEnd`);
      }
    }
    lines.push("  \\resumeSubHeadingListEnd");
    lines.push("");
  }

  
  if (d.education.length) {
    lines.push("%-----------EDUCATION-----------");
    lines.push("\\section{Education}");
    lines.push("  \\resumeSubHeadingListStart");
    for (const ed of d.education) {
      const degree = ed.field ? `${texEscape(ed.degree)} in ${texEscape(ed.field)}` : texEscape(ed.degree);
      const gpa = ed.gpa ? `, GPA: ${texEscape(ed.gpa)}` : "";
      const loc = ed.location ? texEscape(ed.location) : "";
      const edStart = texDate(ed.startDate);
      const edEnd = texDate(ed.endDate);
      const edDates = edStart && edEnd ? `${edStart} -- ${edEnd}` : edStart || edEnd || "";
      lines.push(`    \\resumeSubheading`);
      lines.push(`      {${texEscape(ed.school)}}{${texEscape(edDates)}}`);
      lines.push(`      {${degree}${gpa}}{${loc}}`);
    }
    lines.push("  \\resumeSubHeadingListEnd");
    lines.push("");
  }

  
  if (d.skills.length) {
    lines.push("%-----------SKILLS-----------");
    lines.push("\\section{Skills}");
    lines.push("  \\resumeSubHeadingListStart");
    lines.push("    \\item{");
    lines.push("      \\begin{tabular}{l@{\\hspace{0.5em}}l}");
    for (const s of d.skills) {
      lines.push(`        \\textbf{${texEscape(s.category)}}: & ${texEscape(s.items.join(", "))} \\\\`);
    }
    lines.push("      \\end{tabular}");
    lines.push("    }");
    lines.push("  \\resumeSubHeadingListEnd");
    lines.push("");
  }

  
  if (d.certificates.length) {
    lines.push("%-----------CERTIFICATIONS-----------");
    lines.push("\\section{Certifications}");
    lines.push("  \\resumeSubHeadingListStart");
    lines.push("    \\item{");
    lines.push("      \\begin{tabular*}{0.97\\textwidth}{l@{\\extracolsep{\\fill}}r}");
    for (const c of d.certificates) {
      const dateStr = texDate(c.date);
      const leftSide = `\\textbf{${texEscape(c.name)}}: ${texEscape(c.issuer)}`;
      const rightParts: string[] = [];
      if (dateStr) rightParts.push(dateStr);
      if (c.url) rightParts.push(`\\href{${texEscape(c.url)}}{\\underline{Link}}`);
      const rightSide = rightParts.join(" | ");
      lines.push(`        ${leftSide} & ${rightSide} \\\\`);
    }
    lines.push("      \\end{tabular*}");
    lines.push("    }");
    lines.push("  \\resumeSubHeadingListEnd");
    lines.push("");
  }

  if (d.achievements?.length) {
    lines.push("%-----------ACHIEVEMENTS-----------");
    lines.push("\\section{Achievements}");
    lines.push("  \\resumeSubHeadingListStart");
    for (const a of d.achievements) {
      const desc = a.description ? ` \\textbar{}\\ ${texEscape(a.description)}` : "";
      const rightCol = a.date || a.url ? `${texDate(a.date)}${a.date && a.url ? " " : ""}${a.url ? texEscape(a.url) : ""}` : "";
      lines.push(`      \\resumeProjectHeading`);
      lines.push(`          {\\textbf{${texEscape(a.title)}}${desc}}{${texEscape(rightCol)}}`);
      if (a.bullets.length) {
        lines.push(`          \\resumeItemListStart`);
        for (const b of a.bullets) lines.push(`            \\resumeItem{${texEscape(b)}}`);
        lines.push(`          \\resumeItemListEnd`);
      }
    }
    lines.push("  \\resumeSubHeadingListEnd");
    lines.push("");
  }

  lines.push("\\end{document}");
  return lines.join("\n");
}

function modernCV(d: ResumeData, accent: string): string {
  const hex = accent.replace("#", "").toUpperCase();
  return `% ModernCV — compile with XeLaTeX/LuaLaTeX on Overleaf.
% Requires the moderncv package (available in Overleaf's templates gallery).
\\documentclass[11pt,a4paper]{moderncv}
\\moderncvstyle{classic}
\\moderncvcolor{custom}
\\definecolor{color1}{HTML}{${hex}}
\\usepackage[scale=0.75]{geometry}
\\firstname{${texEscape(d.contact.name.split(" ")[0] || "")}}
\\familyname{${texEscape(d.contact.name.split(" ").slice(1).join(" ") || "")}}
\\title{${texEscape(d.contact.title)}}
\\address{${texEscape(d.contact.location)}}{}{}
\\phone{${texEscape(d.contact.phone)}}
\\email{${texEscape(d.contact.email)}}
\\homepage{${texEscape(d.contact.website || "")}}
\\social[linkedin]{${texEscape((d.contact.linkedin || "").replace(/^.*\//, ""))}}
\\social[github]{${texEscape((d.contact.github || "").replace(/^.*\//, ""))}}

\\begin{document}
\\makecvtitle
${d.summary ? `\\section{Summary}\n${texEscape(d.summary)}\n` : ""}
\\section{Experience}
\\closesection
\\begin{itemize}
${d.experience
  .map(
    (e) =>
      `  \\item \\textbf{${texEscape(e.role)}, ${texEscape(e.company)}} \\hfill ${texDate(e.startDate)}--${e.current ? "Present" : texDate(e.endDate)}\n${e.bullets.map((b) => `    \\begin{itemize} \\item ${texEscape(b)} \\end{itemize}`).join("\n")}`,
  )
  .join("\n")}
\\end{itemize}
${d.projects.length ? `\\section{Projects}\n\\begin{itemize}\n${d.projects.map((p) => `  \\item \\textbf{${texEscape(p.name)}}${p.tech.length ? ` \\emph{(${texEscape(p.tech.join(", "))})}` : ""}\n${p.bullets.map((b) => `    \\begin{itemize} \\item ${texEscape(b)} \\end{itemize}`).join("\n")}`).join("\n")}\n\\end{itemize}\n` : ""}
\\section{Education}
${d.education.map((ed) => `\\cventry{${texDate(ed.startDate)}--${texDate(ed.endDate)}}{${texEscape(ed.degree)}}{${texEscape(ed.school)}}{}{}{${ed.gpa ? `GPA: ${texEscape(ed.gpa)}` : ""}}`).join("\n")}
\\section{Skills}
${d.skills.map((s) => `\\cvitem{${texEscape(s.category)}}{${texEscape(s.items.join(", "))}}`).join("\n")}
${d.certificates.length ? `\\section{Certifications}\n${d.certificates.map((c) => `\\cvitem{${texEscape(c.name)}}{${texEscape(c.issuer)} (${texDate(c.date)})}`).join("\n")}` : ""}
\\end{document}
`;
}

function altaCV(d: ResumeData, accent: string): string {
  const hex = accent.replace("#", "").toUpperCase();
  return `% AltaCV — compile with XeLaTeX on Overleaf.
% Requires the AltaCV class (available in Overleaf's templates gallery).
\\documentclass[10pt,letterpaper]{altacv}
\\geometry{left=1cm,right=9mm,marginparwidth=6.8cm,marginparsep=8mm,top=1.25cm,bottom=1.25cm}
\\usepackage[utf8]{inputenc}
\\definecolor{accent}{HTML}{${hex}}
\\definecolor{darkgray}{HTML}{333333}
\\definecolor{gray}{HTML}{4D4D4D}
\\definecolor{lightgray}{HTML}{999999}
\\color{darkgray}
\\setlettercolor{accent}

\\name{${texEscape(d.contact.name)}}
\\tagline{${texEscape(d.contact.title)}}
\\personalinfo{\\email{${texEscape(d.contact.email)}} \\phone{${texEscape(d.contact.phone)}} \\location{${texEscape(d.contact.location)}} \\homepage{${texEscape(d.contact.website || "")}}}

\\begin{document}
\\makecvheader
${d.summary ? `\\cvsection{Summary}\n${texEscape(d.summary)}\n` : ""}
\\cvsection{Experience}
${d.experience
  .map(
    (e) =>
      `\\cvevent{${texEscape(e.role)}}{${texEscape(e.company)}}{${texDate(e.startDate)} -- ${e.current ? "Present" : texDate(e.endDate)}}{${texEscape(e.location || "")}}\n\\begin{itemize}\n${e.bullets.map((b) => `  \\item ${texEscape(b)}`).join("\n")}\n\\end{itemize}`,
  )
  .join("\n\n")}
${d.projects.length ? `\\cvsection{Projects}\n${d.projects.map((p) => `\\cvevent{${texEscape(p.name)}}{${texEscape(p.tech.join(", "))}}{}{}\n\\begin{itemize}\n${p.bullets.map((b) => `  \\item ${texEscape(b)}`).join("\n")}\n\\end{itemize}`).join("\n\n")}` : ""}
\\cvsection{Skills}
\\cvtag{${d.skills.flatMap((s) => s.items).slice(0, 18).map(texEscape).join("}} \\cvtag{")}}
\\cvsection{Education}
${d.education.map((ed) => `\\cvevent{${texEscape(ed.degree)}}{${texEscape(ed.school)}}{${texDate(ed.startDate)} -- ${texDate(ed.endDate)}}{${ed.gpa ? `GPA: ${texEscape(ed.gpa)}` : ""}}`).join("\n\n")}
${d.certificates.length ? `\\cvsection{Certifications}\n${d.certificates.map((c) => `\\cvitem{${texEscape(c.name)}}{${texEscape(c.issuer)} (${texDate(c.date)})}`).join("\n")}` : ""}
\\end{document}
`;
}


export function toHTML(doc: ResumeDocument): string {
  const d = doc.data;
  const accent = doc.meta.accent;
  const esc = (s: string) =>
    s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
  return `<!doctype html><html><head><meta charset="utf-8"><title>${esc(doc.title)}</title>
<style>
  body{font-family:Calibri,Arial,sans-serif;max-width:780px;margin:32px auto;color:#111;line-height:1.45}
  h1{font-size:26px;margin:0;color:${accent}}
  h2{font-size:14px;text-transform:uppercase;letter-spacing:.08em;border-bottom:2px solid ${accent};padding-bottom:3px;margin-top:22px;color:${accent}}
  .title{font-size:15px;color:#444;margin-bottom:4px}
  .contact{font-size:13px;color:#444;margin-bottom:12px}
  .exp{margin-bottom:10px}
  .role{font-weight:700}
  .meta{float:right;color:#666;font-size:13px}
  ul{margin:4px 0;padding-left:18px}
  li{margin-bottom:3px}
</style></head><body>
<h1>${esc(d.contact.name)}</h1>
<div class="title">${esc(d.contact.title)}</div>
<div class="contact">${esc([d.contact.email, d.contact.phone, d.contact.location, d.contact.website, d.contact.linkedin, d.contact.github].filter(Boolean).join(" • "))}</div>
${d.summary ? `<h2>Summary</h2><p>${esc(d.summary)}</p>` : ""}
${d.experience.length ? `<h2>Experience</h2>${d.experience
    .map(
      (e) =>
        `<div class="exp"><span class="role">${esc(e.role)}</span>, ${esc(e.company)} <span class="meta">${esc(e.startDate)} – ${esc(e.endDate)}</span><ul>${e.bullets.map((b) => `<li>${esc(b)}</li>`).join("")}</ul></div>`,
    )
    .join("")}` : ""}
${d.projects.length ? `<h2>Projects</h2>${d.projects
    .map(
      (p) =>
        `<div class="exp"><span class="role">${esc(p.name)}</span>${p.tech.length ? ` — <em>${esc(p.tech.join(", "))}</em>` : ""}<ul>${[p.description, ...p.bullets].filter(Boolean).map((b) => `<li>${esc(b)}</li>`).join("")}</ul></div>`,
    )
    .join("")}` : ""}
${d.skills.length ? `<h2>Skills</h2><ul>${d.skills.map((s) => `<li><strong>${esc(s.category)}:</strong> ${esc(s.items.join(", "))}</li>`).join("")}</ul>` : ""}
${d.education.length ? `<h2>Education</h2>${d.education.map((ed) => `<div class="exp"><span class="role">${esc(ed.degree)}${ed.field ? `, ${esc(ed.field)}` : ""}</span>, ${esc(ed.school)} <span class="meta">${esc(ed.startDate)} – ${esc(ed.endDate)}</span></div>`).join("")}` : ""}
${d.certificates.length ? `<h2>Certifications</h2><ul>${d.certificates.map((c) => `<li><strong>${esc(c.name)}</strong> — ${esc(c.issuer)} (${esc(c.date)})</li>`).join("")}</ul>` : ""}
</body></html>`;
}

export function downloadFile(filename: string, content: string, mime = "text/plain") {
  const blob = new Blob([content], { type: `${mime};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}






function fmtDateFull(s: string | undefined): string {
  if (!s) return "";
  const m = s.match(/^(\d{4})-(\d{1,2})$/);
  if (m) {
    const months = [
      "January","February","March","April","May","June",
      "July","August","September","October","November","December",
    ];
    return `${months[parseInt(m[2], 10) - 1]} ${m[1]}`;
  }

  return s;
}

type FontKey = "inter" | "geist" | "serif" | "mono";

const FONT_CONFIG: Record<FontKey, { stack: string; google: string }> = {
  serif: {
    stack: "'Lora','DejaVu Serif','Times New Roman',Times,serif",
    google: "Lora:wght@400;500;600;700",
  },
  mono: {
    stack: "'JetBrains Mono','DejaVu Sans Mono','Courier New',monospace",
    google: "JetBrains+Mono:wght@400;500;600;700",
  },
  geist: {
    stack: "'Geist','Inter','DejaVu Sans',sans-serif",
    google: "Geist:wght@400;500;600;700",
  },
  inter: {
    stack: "'Inter','DejaVu Sans',sans-serif",
    google: "Inter:wght@400;500;600;700",
  },
};

function fontLink(font: FontKey): string {
  const fam = FONT_CONFIG[font].google;
  return `<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=${fam}&display=swap" rel="stylesheet">`;
}

function htmlEsc(s: string | undefined): string {
  return (s ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

export function toPrintableHTML(doc: ResumeDocument, pageSize: PageSize = "letter"): string {
  const d = doc.data;
  const accent = doc.meta.accent || "#0f766e";
  const pageDim = PAPER_DIM[pageSize];
  const fontKey: FontKey = (doc.meta.font in FONT_CONFIG ? doc.meta.font : "inter") as FontKey;
  const fontStack = FONT_CONFIG[fontKey].stack;
  const esc = htmlEsc;

  const contactParts = [
    d.contact.email,
    d.contact.phone,
    d.contact.location,
    d.contact.website,
    d.contact.linkedin,
    d.contact.github,
  ].filter((v): v is string => Boolean(v)).map(esc);
  
  const contactLine = contactParts.join(" &nbsp;|&nbsp; ");

  
  const expHTML = d.experience.map((e) => {
    const dates = `${esc(fmtDateFull(e.startDate))} – ${e.current ? "Present" : esc(fmtDateFull(e.endDate))}`;
    return `
      <div class="entry">
        <div class="entry-head">
          <span class="entry-title">${esc(e.role)}</span>
          <span class="entry-dates">${dates}</span>
        </div>
        <div class="entry-sub">${esc(e.company)}${e.location ? `, ${esc(e.location)}` : ""}</div>
        ${e.bullets.length ? `<ul>${e.bullets.map((b) => `<li>${esc(b)}</li>`).join("")}</ul>` : ""}
      </div>`;
  }).join("");

  const projHTML = d.projects.length ? `
    <section class="section">
      <h2>Projects</h2>
      ${d.projects.map((p) => {
        const dateRange = p.startDate || p.endDate ? `${esc(fmtDateFull(p.startDate))}${p.endDate ? " \u2013 " + esc(fmtDateFull(p.endDate)) : ""}` : "";
        return `
        <div class="entry">
          <div class="entry-head">
            <span class="entry-title">${esc(p.name)}${p.tech.length ? ` <span class="tech-inline">| ${esc(p.tech.join(", "))}</span>` : ""}</span>
            ${dateRange ? `<span class="entry-dates">${dateRange}</span>` : ""}
          </div>
          ${p.description ? `<div class="entry-sub">${esc(p.description)}</div>` : ""}
          ${p.bullets.length ? `<ul>${p.bullets.map((b) => `<li>${esc(b)}</li>`).join("")}</ul>` : ""}
        </div>`}).join("")}
    </section>` : "";

  const trainingHTML = d.training?.length ? `
    <section class="section">
      <h2>Summer Training</h2>
      ${d.training.map((t) => {
        const dates = `${esc(fmtDateFull(t.startDate))} \u2013 ${esc(fmtDateFull(t.endDate))}`;
        return `
        <div class="entry">
          <div class="entry-head">
            <span class="entry-title">${esc(t.title)}</span>
            <span class="entry-dates">${dates}</span>
          </div>
          ${t.organization ? `<div class="entry-sub">${esc(t.organization)}</div>` : ""}
          ${t.bullets.length ? `<ul>${t.bullets.map((b) => `<li>${esc(b)}</li>`).join("")}</ul>` : ""}
        </div>`}).join("")}
    </section>` : "";

  const achHTML = d.achievements?.length ? `
    <section class="section">
      <h2>Achievements</h2>
      ${d.achievements.map((a) => {
        const rightInfo = [a.date, a.url].filter(Boolean).map(esc).join(" | ");
        return `
        <div class="entry">
          <div class="entry-head">
            <span class="entry-title">${esc(a.title)}</span>
            ${rightInfo ? `<span class="entry-dates">${rightInfo}</span>` : ""}
          </div>
          ${a.description ? `<div class="entry-sub">${esc(a.description)}</div>` : ""}
          ${a.bullets.length ? `<ul>${a.bullets.map((b) => `<li>${esc(b)}</li>`).join("")}</ul>` : ""}
        </div>`}).join("")}
    </section>` : "";

  
  const skillsHTML = d.skills.length ? `
    <section class="section">
      <h2>Skills</h2>
      ${d.skills.map((s) => `<div class="skill-line"><span class="skill-cat">${esc(s.category)}:</span> ${esc(s.items.join(", "))}</div>`).join("")}
    </section>` : "";

  const eduHTML = d.education.length ? `
    <section class="section">
      <h2>Education</h2>
      ${d.education.map((ed) => `
        <div class="entry">
          <div class="entry-head">
            <span class="entry-title">${esc(ed.degree)}${ed.field ? ` in ${esc(ed.field)}` : ""}</span>
            <span class="entry-dates">${esc(fmtDateFull(ed.startDate))} \u2013 ${esc(fmtDateFull(ed.endDate))}</span>
          </div>
          <div class="entry-sub">${esc(ed.school)}${ed.location ? `, ${esc(ed.location)}` : ""}${ed.gpa ? ` \u00b7 GPA: ${esc(ed.gpa)}` : ""}</div>
        </div>`).join("")}
    </section>` : "";

  const certHTML = d.certificates.length ? `
    <section class="section">
      <h2>Certifications</h2>
      <ul>
        ${d.certificates.map((c) => {
          const parts = [esc(c.issuer)];
          if (c.date) parts.push(esc(fmtDateFull(c.date)));
          if (c.url) parts.push(`<a href="${esc(c.url)}" style="color:${accent};text-decoration:none;">Link</a>`);
          return `<li><strong>${esc(c.name)}</strong> — ${parts.join(" | ")}</li>`;
        }).join("")}
      </ul>
    </section>` : "";

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(d.contact.name)} — ${esc(d.contact.title)}</title>
${fontLink(fontKey)}
<style>
  @page { size: ${pageDim}; margin: 0.5in; }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  html, body {
    font-family: ${fontStack};
    font-size: 10.5pt;
    line-height: 1.4;
    color: #111111;
    background: #ffffff;
    -webkit-print-color-adjust: exact;
    print-color-adjust: exact;
  }

  /* ---- Header (name + title + contact) ---- */
  .header {
    text-align: center;
    margin-bottom: 14px;
    padding-bottom: 10px;
    border-bottom: 1.5pt solid ${accent};
  }
  .header h1 {
    font-size: 20pt;
    font-weight: 700;
    letter-spacing: 0.01em;
    color: #111111;
    margin-bottom: 1px;
  }
  .header .title {
    font-size: 11pt;
    color: ${accent};
    font-weight: 600;
  }
  .header .contact {
    font-size: 9.5pt;
    color: #444444;
    margin-top: 5px;
  }

  /* ---- Section headings: standard, uppercase, ATS-recognizable ---- */
  .section { margin-bottom: 12px; page-break-inside: avoid; }
  h2 {
    font-size: 10.5pt;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.06em;
    color: ${accent};
    border-bottom: 0.5pt solid ${accent};
    padding-bottom: 2px;
    margin-bottom: 7px;
    page-break-after: avoid;
  }

  /* ---- Experience / education / project entries ---- */
  .entry { margin-bottom: 9px; page-break-inside: avoid; }
  .entry-head {
    display: flex;
    justify-content: space-between;
    align-items: baseline;
    gap: 8px;
    flex-wrap: wrap;
  }
  .entry-title { font-weight: 700; font-size: 10.5pt; color: #111111; flex: 1 1 auto; min-width: 0; }
  .entry-dates { font-size: 9.5pt; color: #555555; white-space: nowrap; flex: 0 0 auto; }
  .tech-inline { font-weight: 400; color: #666666; font-style: italic; }
  .entry-sub { font-size: 10pt; color: ${accent}; font-weight: 600; margin-top: 1px; margin-bottom: 2px; }

  /* ---- Bullets: plain disc, indented — ATS reads these reliably ---- */
  ul {
    margin: 3px 0 0 0;
    padding-left: 18px;
    list-style: disc;
  }
  li {
    margin-bottom: 2px;
    font-size: 10pt;
    color: #222222;
    line-height: 1.4;
    page-break-inside: avoid;
  }

  /* ---- Skills: single-column lines, not a grid ---- */
  .skill-line { font-size: 10pt; margin-bottom: 2px; color: #222222; }
  .skill-cat { font-weight: 700; color: #111111; }

  /* ---- Summary paragraph ---- */
  .summary { font-size: 10pt; color: #333333; line-height: 1.45; }

  /* Screen preview wrapper (Puppeteer ignores this; it only prints the body) */
  @media screen {
    body { background: #f5f5f5; padding: 20px; }
    .page {
      max-width: 8.5in;
      margin: 0 auto;
      background: #fff;
      padding: 0.5in 0.6in;
      box-shadow: 0 4px 24px rgba(0,0,0,0.1);
    }
  }
  @media print {
    .page { padding: 0; max-width: none; box-shadow: none; }
  }
</style>
</head>
<body>
<div class="page">
  <header class="header">
    <h1>${esc(d.contact.name)}</h1>
    ${d.contact.title ? `<div class="title">${esc(d.contact.title)}</div>` : ""}
    ${contactLine ? `<div class="contact">${contactLine}</div>` : ""}
  </header>

  ${d.summary ? `<section class="section"><h2>Professional Summary</h2><p class="summary">${esc(d.summary)}</p></section>` : ""}

  ${d.experience.length ? `<section class="section"><h2>Work Experience</h2>${expHTML}</section>` : ""}
  ${projHTML}
  ${trainingHTML}
  ${skillsHTML}
  ${eduHTML}
  ${certHTML}
  ${achHTML}
</div>
</body>
</html>`;
}

export function toLatexStyleHTML(doc: ResumeDocument, pageSize: PageSize = "letter"): string {
  const d = doc.data;
  const accent = doc.meta.accent || "#0f766e";
  const pageDim = PAPER_DIM[pageSize];
  const esc = htmlEsc;

  const contactParts = [
    d.contact.email,
    d.contact.phone,
    d.contact.location,
    d.contact.website,
    d.contact.linkedin,
    d.contact.github,
  ].filter((v): v is string => Boolean(v)).map(esc);
  const contactLine = contactParts.join(" &nbsp;|&nbsp; ");

  const section = (title: string, inner: string): string =>
    inner ? `<section class="sec"><h2>${esc(title)}</h2>${inner}</section>` : "";

  const expHTML = d.experience.map((e) => {
    const dates = `${esc(fmtDateFull(e.startDate))} — ${e.current ? "Present" : esc(fmtDateFull(e.endDate))}`;
    return `<div class="item">
      <div class="item-head"><span class="item-title">${esc(e.role)}</span><span class="item-dates">${dates}</span></div>
      <div class="item-sub">${esc(e.company)}${e.location ? `, ${esc(e.location)}` : ""}</div>
      ${e.bullets.length ? `<ul>${e.bullets.map((b) => `<li>${esc(b)}</li>`).join("")}</ul>` : ""}
    </div>`;
  }).join("");

  const projHTML = d.projects.map((p) => {
    const dateRange = p.startDate || p.endDate ? `${esc(fmtDateFull(p.startDate))}${p.endDate ? " — " + esc(fmtDateFull(p.endDate)) : ""}` : "";
    return `<div class="item">
      <div class="item-head"><span class="item-title">${esc(p.name)}${p.tech.length ? ` <em class="tech-inline">| ${esc(p.tech.join(", "))}</em>` : ""}</span>${dateRange ? `<span class="item-dates">${dateRange}</span>` : ""}</div>
      ${p.description ? `<div class="item-sub">${esc(p.description)}</div>` : ""}
      ${p.bullets.length ? `<ul>${p.bullets.map((b) => `<li>${esc(b)}</li>`).join("")}</ul>` : ""}
    </div>`;
  }).join("");

  const eduHTML = d.education.map((ed) => `
    <div class="item">
      <div class="item-head"><span class="item-title">${esc(ed.degree)}${ed.field ? ` in ${esc(ed.field)}` : ""}</span><span class="item-dates">${esc(fmtDateFull(ed.startDate))} — ${esc(fmtDateFull(ed.endDate))}</span></div>
      <div class="item-sub">${esc(ed.school)}${ed.location ? `, ${esc(ed.location)}` : ""}${ed.gpa ? ` &middot; GPA: ${esc(ed.gpa)}` : ""}</div>
    </div>`).join("");

  const skillsHTML = d.skills.map((s) => `<div class="skill-row"><span class="skill-cat">${esc(s.category)}:</span> ${esc(s.items.join(", "))}</div>`).join("");

  const certHTML = d.certificates.length ? `<ul>${d.certificates.map((c) => {
    const parts = [esc(c.issuer)];
    if (c.date) parts.push(esc(fmtDateFull(c.date)));
    return `<li><strong>${esc(c.name)}</strong> — ${parts.join(" &nbsp;|&nbsp; ")}</li>`;
  }).join("")}</ul>` : "";

  const trainHTML = d.training.map((t) => {
    const dates = `${esc(fmtDateFull(t.startDate))} — ${esc(fmtDateFull(t.endDate))}`;
    return `<div class="item">
      <div class="item-head"><span class="item-title">${esc(t.title)}</span><span class="item-dates">${dates}</span></div>
      ${t.organization ? `<div class="item-sub">${esc(t.organization)}</div>` : ""}
      ${t.bullets.length ? `<ul>${t.bullets.map((b) => `<li>${esc(b)}</li>`).join("")}</ul>` : ""}
    </div>`;
  }).join("");

  const achHTML = d.achievements.map((a) => {
    const right = [a.date, a.url].filter(Boolean).map(esc).join(" &nbsp;|&nbsp; ");
    return `<div class="item">
      <div class="item-head"><span class="item-title">${esc(a.title)}</span>${right ? `<span class="item-dates">${right}</span>` : ""}</div>
      ${a.description ? `<div class="item-sub">${esc(a.description)}</div>` : ""}
      ${a.bullets.length ? `<ul>${a.bullets.map((b) => `<li>${esc(b)}</li>`).join("")}</ul>` : ""}
    </div>`;
  }).join("");

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(d.contact.name)} — ${esc(d.contact.title)}</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Lora:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500;600;700&display=swap" rel="stylesheet">
<style>
  @page { size: ${pageDim}; margin: 0.5in; }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  html, body {
    font-family: 'Lora','DejaVu Serif','Times New Roman',Times,serif;
    font-size: 10.5pt;
    line-height: 1.38;
    color: #111;
    background: #fff;
    -webkit-print-color-adjust: exact;
    print-color-adjust: exact;
  }
  .page { padding: 0 0.05in; }
  .name {
    text-align: center;
    font-size: 22pt;
    font-weight: 700;
    letter-spacing: 0.02em;
    padding-bottom: 4pt;
    border-bottom: 1pt solid #111;
    margin-bottom: 4pt;
  }
  .contact {
    text-align: center;
    font-size: 10pt;
    color: #333;
    margin-bottom: 10pt;
  }
  .sec { margin-bottom: 9pt; page-break-inside: avoid; }
  h2 {
    font-size: 11pt;
    font-weight: 700;
    font-variant: small-caps;
    letter-spacing: 0.04em;
    color: #111;
    border-bottom: 0.6pt solid #111;
    padding-bottom: 1.5pt;
    margin-bottom: 5pt;
    page-break-after: avoid;
  }
  .item { margin-bottom: 7pt; page-break-inside: avoid; }
  .item-head {
    display: flex;
    justify-content: space-between;
    align-items: baseline;
    gap: 8px;
    flex-wrap: wrap;
  }
  .item-title { font-weight: 700; font-size: 10.5pt; }
  .item-dates { font-size: 9.5pt; color: #555; white-space: nowrap; }
  .item-sub { font-size: 10pt; font-style: italic; color: #444; margin-top: 1px; margin-bottom: 2px; }
  ul { margin: 2pt 0 0 0; padding-left: 16pt; list-style: disc; }
  li { font-size: 10pt; margin-bottom: 1.5pt; line-height: 1.38; page-break-inside: avoid; }
  .skill-row { font-size: 10pt; margin-bottom: 1.5pt; }
  .skill-cat { font-weight: 700; }
  .summary { font-size: 10pt; color: #222; line-height: 1.42; }
</style>
</head>
<body>
<div class="page">
  <div class="name">${esc(d.contact.name)}</div>
  <div class="contact">${contactLine}</div>
  ${d.summary ? section("Summary", `<p class="summary">${esc(d.summary)}</p>`) : ""}
  ${d.experience.length ? section("Experience", expHTML) : ""}
  ${d.projects.length ? section("Projects", projHTML) : ""}
  ${d.training.length ? section("Summer Training", trainHTML) : ""}
  ${d.skills.length ? section("Skills", skillsHTML) : ""}
  ${d.education.length ? section("Education", eduHTML) : ""}
  ${d.certificates.length ? section("Certifications", certHTML) : ""}
  ${d.achievements.length ? section("Achievements", achHTML) : ""}
</div>
</body>
</html>`;
}


export { fmtDateFull };
